apiVersion: v1
kind: Service              
metadata:
  name: terminal-application-lb
spec:
  type: LoadBalancer       
  ports:
  - port: 80               
    protocol: TCP          
    targetPort: 80         
  selector:                
    app: terminal-application       