apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: terminal-application
  labels:
    app: terminal-application
spec:
  selector:
    matchLabels:
      app: terminal-application
  replicas: 2                                             
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1                                         
  template:
    metadata:
      labels:
        app: terminal-application                                  
    spec:
      containers:
        - image: anyuanyu/project-terminal-application
          imagePullPolicy: Always                         
          name: terminal-application
          ports:
            - containerPort: 80
