apiVersion: apps/v1
apiVersion: v1
kind: Service
metadata:
  labels:
    app:  spark-service
  name:  spark-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31749
  selector:
    app:  spark-service
  type: NodePort