apiVersion: v1
kind: Service
metadata:
  name: sonar
spec:
  type: LoadBalancer
  loadBalancerIP: 34.138.10.197
  ports:
    - port:  80
      protocol: TCP
      targetPort: 80
  selector:
    app: app-sonar